### ISSUE TITLE
Build not starting

### ISSUE THREAD

**Issue by Boeblahoebla** [wbkd/webpack-starter#103]
Hi

When trying to build a project, the build doesn't seem to start. 
@ First I couldn't star the build. I needed to put the 'set' command before NODE_ENV in the build script. Afterwards I could run the command 'npm run build' but the the process only starts for a split second. There's no build folder, but also no error message.

Any advice? Keep up the good work with this repo! I'm using it quite a lot

Cheerz

**Comment by moklick** [comment]
I added `cross-env` for running the build script. Could you check if it's working for you now?

**Comment by pierresis** [comment]
It works for me ;)
