### ISSUE TITLE
Add stylelint and postcss

### ISSUE THREAD

**Issue by jkevingutierrez** [wbkd/webpack-starter#105]
Great project!

It would be good to add stylelint and postcss (autoprefixer, cssnano)

**Comment by timvancleef** [comment]
In https://github.com/wbkd/webpack-starter/pull/273 i added stylelint and postcss.
I left out cssnano though, because the CSS bundle already gets minified by webpack's optimization feature.

**Comment by jkevingutierrez** [comment]
Added in #273
