### ISSUE TITLE
npm error messages

### ISSUE THREAD

**Issue by jcovington16** [wbkd/webpack-starter#16]
I am using visual code as my editor. I copied your link and downloaded everything through my cmd prompt (windows). I tried installing everything and I am getting an error message when I use npm run dev to start up the server. I also tried using npm start and still keep getting the error message saying "scripts missing" or what not. Could you please help me fix the issue. I am doing a tutorial through plural sight and working of course with java script. Thank you for your help.

**Comment by Marcelo00** [comment]
Hi,
I had the same problem. I solved this by checking the version of the modules webpack and webpack-dev-server and if necessary, downgrading these modules. What versions are you using?

**Comment by moklick** [comment]
I' ve just updated the dependencies. Could you check if you still have any problems? If so, please point out your node version and error logs.
