### ISSUE TITLE
Include purge css

### ISSUE THREAD

**Issue by vivek1996** [wbkd/webpack-starter#17]
Please include purge css in the config or provide the procedure for adding autoprefixer, cssnano and purge css for production build.

**Comment by moklick** [comment]
we want to keep this as light as possible.. you can easily add a postcss loader to the config if you need it

**Comment by tompha** [comment]
@moklick Can you please explain how to add postcss with autoprefixer? Would greatly help!

**Comment by moklick** [comment]
@tompha you can find it in the postcss loader docs https://github.com/postcss/postcss-loader#autoprefixing
