### ISSUE TITLE
npm ERR! missing script: dev

### ISSUE THREAD

**Issue by davieoba** [wbkd/webpack-starter#19]
when I run the code 'npm run dev' in the terminal it outputs the error 'npm ERR! missing script: dev'.
[npm-debug.log](https://github.com/wbkd/webpack-starter/files/2518232/npm-debug.log)

**Comment by g-div** [comment]
There is no `npm run dev` script. Just `npm start`.

**Comment by davieoba** [comment]
thanks problem is fixed !

**Comment by gs-jvunnam** [comment]
When I type the command  in my terminal in VS Code , browser opened up http://localhost:8080/
but the changes made to index.js are not reflected in browser ?
Am I doing something wrong here ?
