### ISSUE TITLE
error on npm install (primordials is not defined)

### ISSUE THREAD

**Issue by michaelcerrato** [wbkd/webpack-starter#205]
Hello, I am having an issue running npm install.  Is this related to webpack-starter?

$ npm install
npm ERR! Windows_NT 10.0.18362
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mike\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v12.16.2
npm ERR! npm  v3.6.0

npm ERR! primordials is not defined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\mike\jsdev\webpack-starter\npm-debug.log

Thank you!

**Comment by moklick** [comment]
Hey, we can't reproduce this. Do you still get this error with the latest version?

**Comment by mtempro** [comment]
I have the same issue

**Comment by githumbi** [comment]
having same issue

**Comment by moklick** [comment]
I just updated the packages
