### ISSUE TITLE
Not resolving image path in HTML inline style

### ISSUE THREAD

**Issue by akimcsm** [wbkd/webpack-starter#21]
I'm trying to load a background image like so:
`<div class="page-header" style="background-image: url('./img/background.jpg')">`
but I get a 404 on the image url. The `img` folder is inside `src`.
I've also tried writing it like this `url('~img/background.jpg')` but I get the same result. Can you please let me know how I can solve this? Thanks!

**Comment by moklick** [comment]
Hey guys,

we are copying the [public folder to the dist folder](https://github.com/wbkd/webpack-starter/blob/master/webpack/webpack.common.js#L22-L24). So when you image is inside the public folder you can do: `<img src="/public/webkid.jpg" />` in your html.
