### ISSUE TITLE
Open Chrome or edge instead of IE

### ISSUE THREAD

**Issue by eliassal** [wbkd/webpack-starter#214]
Hi, I have Chrome and Edge on my win10 box. When I do npm start, it luaunches IE instead of those 2 browsers.
After googling, I adde a bs-config.json in the root, restart, still opens IE11
Thanks

**Comment by moklick** [comment]
I think it opens your default browser

**Comment by eliassal** [comment]
OK, IE is not my default browser, it is Chrome, this is why I need to know how to control it?
