### ISSUE TITLE
Why index.js is executed

### ISSUE THREAD

**Issue by eliassal** [wbkd/webpack-starter#219]
Hi, can you please tell me when we do 
npm start
index.js is executed? It is not referenced in index.html, so what is making it getting executed?
I added a ne js file in src/scripts but it does not get executed
Thanks

**Comment by moklick** [comment]
Hi,

the `index.js` file is executed, because it is the entry point of the webpack config https://github.com/wbkd/webpack-starter/blob/master/webpack/webpack.common.js#L8

If you want to execute another file, you can import in index.js

**Comment by eliassal** [comment]
Thanks
