### ISSUE TITLE
npm start -> npm run start

### ISSUE THREAD

**Issue by Rrrr4321** [wbkd/webpack-starter#228]
I'm a first timer in this and found that npm run start gave me the dev server, not npm run:

package.json:
"scripts": {
    "build": "cross-env NODE_ENV=production webpack --config webpack/webpack.config.prod.js --colors",
    "start": "webpack-dev-server --open --config webpack/webpack.config.dev.js"
  },

Please verify your instructions in README.md and adjust accordingly if I'm correct.

**Comment by moklick** [comment]
Hey @Rrrr4321 

everything is fine here.

`npm run start` and `npm start` is the same. Both should start the dev server.

**Comment by Rrrr4321** [comment]
I checked and of course you are right. Apologies
