### ISSUE TITLE
how i can design multi page?

### ISSUE THREAD

**Issue by vahidalvandi** [wbkd/webpack-starter#231]
hi , i default have one page index.html . i need about.html ,..??

**Comment by levaiss** [comment]
> hi , i default have one page index.html . i need about.html ,..??

Easy way, it`s add one more instance HtmlWebpackPlugin, like this:

```javascript
plugins: [
        ...
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: Path.resolve(__dirname, '../src/templates/index.html'),
        }),
        new HtmlWebpackPlugin({
            filename: 'test.html',
            template: Path.resolve(__dirname, '../src/templates/test.html')
        }),
    ],
```

**Comment by straube** [comment]
In case you don't want to add an entry to the plugins array for every page, it's possible to add some logic to `webpack.common.js` to handle that. I wrote the following code -- with comments for clarification.

```
// Feel free move this require call to the top of the file
const Fs = require('fs');

// Starts an empty array that will hold all HtmlWebpackPlugin instances
const pages = [];

// Read the src dir
const files = Fs.readdirSync(Path.resolve(__dirname, '../src'));

// Loop through entries in src dir
files.forEach(function (file) {

  // If the entry doesn't have the extension .html, skip it
  if (!file.match(/\.html$/)) {
    return;
  }

  // Creates a new HtmlWebpackPlugin instance for the current entry
  pages.push(new HtmlWebpackPlugin({
    filename: file,
    template: Path.resolve(__dirname, '../src', file),
  }));
});
```

It's important to have the snippet above **before** the `module.exports` declaration.

Then, change the `plugins` array this way:

```
  plugins: [
    ...
    // No HtmlWebpackPlugin instance here
  ].concat(pages),
```

**Comment by alex-drocks** [comment]
> In case you don't want to add an entry to the plugins array for every page, it's possible to add some logic to `webpack.common.js` to handle that. I wrote the following code -- with comments for clarification.
> 
> ```
> // Feel free move this require call to the top of the file
> const Fs = require('fs');
> 
> // Starts an empty array that will hold all HtmlWebpackPlugin instances
> const pages = [];
> 
> // Read the src dir
> const files = Fs.readdirSync(Path.resolve(__dirname, '../src'));
> 
> // Loop through entries in src dir
> files.forEach(function (file) {
> 
>   // If the entry doesn't have the extension .html, skip it
>   if (!file.match(/\.html$/)) {
>     return;
>   }
> 
>   // Creates a new HtmlWebpackPlugin instance for the current entry
>   pages.push(new HtmlWebpackPlugin({
>     filename: file,
>     template: Path.resolve(__dirname, '../src', file),
>   }));
> });
> ```
> 
> It's important to have the snippet above **before** the `module.exports` declaration.
> 
> Then, change the `plugins` array this way:
> 
> ```
> plugins: [
>   ...
>   // No HtmlWebpackPlugin instance here
> ].concat(pages),
> ```

works well thanks a lot!

**Comment by moklick** [comment]
I will close this issue because it's not related to this starter kit but webpack/ HtmlWebpackPlugin in general.
