### ISSUE TITLE
Async Functions / Promises

### ISSUE THREAD

**Issue by vin-ni** [wbkd/webpack-starter#245]
Hello,
is it possible to add support for async functions to the webpack config?

I've found some approaches on how to add it, but couldn't figure it out:
https://medium.com/@tanbt/configure-async-await-es7-in-webpack-4-78adfda46eac

Basically you add this to the entry:
entry: ["@babel/polyfill", "./src/app.js"],

But i can't get it to work. I'd like to be able to run stuff like:
```js
async function hello() { return "Hello" };
hello().then((value) => console.log(value))
```

Thank you!

**Comment by moklick** [comment]
Hey @vin-ni 

that should already work in modern browsers. I have added `babel-eslint` to `eslintrc` so that no warning is shown

**Comment by vin-ni** [comment]
thank you!
