### ISSUE TITLE
CSS is loaded too late

### ISSUE THREAD

**Issue by radkaag** [wbkd/webpack-starter#25]
The best you can see it when you keep reloading the page and for some milliseconds the "webpack starter" text stays black until css is loaded.

**Comment by moklick** [comment]
In development we have HMR for CSS. You won't see this effect in the production build. There we use [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) in order to extract the css. You can find a little note about the in the readme file
