### ISSUE TITLE
ModuleConcatenationPlugin is deprecated

### ISSUE THREAD

**Issue by anatoly314** [wbkd/webpack-starter#264]
`ModuleConcatenationPlugin` is deprecated and `config.optimization.concatenateModules` should be used. Right now try to figure out what needs be changed in `webpack.config.prod.js` after that hopefully will create PR.
https://webpack.js.org/migrate/4/#deprecatedremoved-plugins

**Comment by anatoly314** [comment]
If I understand correctly, `ModuleConcatenationPlugin` can be safely removed in WebPack v4, because:
> By default `optimization.concatenateModules` is enabled in production mode and disabled elsewise.

Can someone who more familiar with WebPack confirm that I'm right?

**Comment by moklick** [comment]
yep, you are right. You are welcome to do a PR :)

**Comment by anatoly314** [comment]
@moklick , done. Btw, do you know similar project but with TypeScript in mind?

**Comment by moklick** [comment]
Thanks for the PR! I used https://github.com/formium/tsdx for a library. Besides that I don't have any recommendations for you.
