### ISSUE TITLE
Add documentation on how to use images

### ISSUE THREAD

**Issue by epicserve** [wbkd/webpack-starter#290]
It would be helpful to add documentation on how to use images in your index.html.

**Comment by epicserve** [comment]
It seems like by adding `contentBase` in `webpack/webpack.config.dev.js` added being able to serve images.

```
...
devServer: {
  inline: true,
  hot: true,
  host: '0.0.0.0',
  contentBase: [__dirname + '/public']
},
...
```

Images that I put in `public/images` were served when I added them in `index.html`.

Example:
```
<img src="/public/images/background1.jpg" alt="Background Image">
```

**Comment by moklick** [comment]
This is not related to this starter kit but to webpack in general. Everything that is inside the `public` folder gets copied. When you have an image `image.jpg` inside the public folder you can do:

`<img src="/public/image.jpg" />` inside your index.html.
