### ISSUE TITLE
Point of public folder(s)?

### ISSUE THREAD

**Issue by caspervanpomeren** [wbkd/webpack-starter#30]
Hi,

I was wondering what the advantage/logic is behind having a folder called "public" with an empty .gitkeep file inside. I found this public folder inside the starter zip and inside the "build" folder after running "npm run build".

After some googling and looking through the configs I still couldn't figure out why they are there. Would love to know.

Thanks!

**Comment by moklick** [comment]
Hey @caspervanpomeren,

you could use the public folder if you want to use a HTML image tag in your index.html for example. See also this issue: https://github.com/wbkd/webpack-starter/issues/21#issuecomment-434608741
