### ISSUE TITLE
npm start not working : node version v10.15.2

### ISSUE THREAD

**Issue by KS488** [wbkd/webpack-starter#31]
npm start not working : node version v10.15.2

**Comment by AndyLnd** [comment]
Hi, could you please provide a little more information? What error message do you get?

**Comment by KS488** [comment]
@AndyLnd 
> webpack-starter@1.0.0 start /Users/khalid/Desktop/JavaScript/Tutorial:Begginers/webpack-starter-master
> webpack-dev-server --open --config webpack/webpack.config.dev.js

sh: webpack-dev-server: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! webpack-starter@1.0.0 start: `webpack-dev-server --open --config webpack/webpack.config.dev.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webpack-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/khalid/.npm/_logs/2019-03-02T14_27_04_897Z-debug.log

**Comment by moklick** [comment]
Hey, did you do `npm install` before?

**Comment by KS488** [comment]
@moklick yes i have and still same error

**Comment by farissi** [comment]
remove node_modules folder
remove package-lock.json
run: npm install
 run: npm start

**Comment by KS488** [comment]
@farissi  still getting the same problem 

> webpack-starter@1.0.0 start /Users/Desktop/JavaScript/Tutorial:Begginers/webpack-starter
> webpack-dev-server --open --config webpack/webpack.config.dev.js

sh: webpack-dev-server: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! webpack-starter@1.0.0 start: `webpack-dev-server --open --config webpack/webpack.config.dev.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webpack-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by moklick** [comment]
try to install it globally `npm install webpack-dev-server -g`

**Comment by KS488** [comment]
@moklick  i get this when i try install it globally

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN webpack-dev-server@3.2.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.6.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by moklick** [comment]
I would recommend to use a node version manager like [nvm](https://github.com/creationix/nvm#install--update-script). It puts node and all the globally installed packages in your user folder , so you won't get any `permission denied` issues. More over it lets you easily switch between node version and install new ones.

**Comment by KS488** [comment]
@moklick Tried both suggestions and this is still an issue

**Comment by KS488** [comment]
Also why would you not recommend in doing this as i have done this aleady : sudo npm install webpack-dev-server -g

**Comment by g-div** [comment]
> Also why would you not recommend in doing this as i have done this aleady : sudo npm install webpack-dev-server -g

Mainly because if you install a package using `sudo` this will be installed by the `root` user and can therefore easily gain root access on your machine, but there are also a lot of other [issues](https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92) with it. 

It seems you are getting `command not found` because you didn't installed the dependencies correctly. Are you sure that you did the following ?
```
git clone https://github.com/wbkd/webpack-starter
cd webpack-starter
npm install

# run
npm start
```
Is `npm install` maybe returning an error ? Is the `node_modules` folder in the project root folder ?
Does the file `./node_modules/.bin/webpack-dev-server` exists ?

**Comment by g-div** [comment]
I hope you solved your issue. I will close this issue due OP inactivity.
Feel free to re-open it if you can add the requested details.

**Comment by dannyjimenez110** [comment]
Resolvi el problema haciendo todo desde el comienzo pero con el usuario root

**Comment by sumbalilyas** [comment]
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2019-05-12T10_08_37_831Z-debug.log


here the error ... before few hours project runs correctly but now its showing error

**Comment by g-div** [comment]
Your problem isn't related to this repository, since there is no `expo start` command here.
