### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mshddev** [wbkd/webpack-starter#362]
Hai, we should add support to typescript.
It would really useful.

**Comment by moklick** [comment]
What are you missing?

**Comment by mshddev** [comment]
config for compiling typescript

**Comment by SalttySugar** [comment]
Everyone needs something.
I think this repository is a starter for basic Webpack config without something specific.
It makes it easier for maintaining, debugging and extending for different use-cases like adding Tailwindcss or Typescript and or flow and so on.

If you wish to create your own starter with typescript just fork/create your own template with config in it.

**Comment by moklick** [comment]
When I answered this issue I thought that I am in another repo :D So here we will not add typescript support.

**Comment by kuncevic** [comment]
@mshddev It seems like if you need a typescript for this one it (may be) means you want to write something complex, if so you might need to consider a proper front-end framework that is properly supports typescript 🤔
