### ISSUE TITLE
npm start not loading scss file

### ISSUE THREAD

**Issue by artworkjpm** [wbkd/webpack-starter#38]
I would like to do "npm start" and then view the scss file being compiled, is this not possible?
I get this error message:
```
ERROR in ./src/scripts/index.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
```

I thought this repo would have everything needed to run sass in dev mode?

**Comment by g-div** [comment]
Yes, it does. Did you edit any file before running `npm start` ? The repo should work with sass/scss out-of-the-box.

**Comment by g-div** [comment]
Closing due inactivity. Feel free to re-open this issue when you can provide further information.
