### ISSUE TITLE
High severity vulnerabilities

### ISSUE THREAD

**Issue by twysto** [wbkd/webpack-starter#41]
To reproduce just clone the master branch then run:

**_`npm install`_**

You should receive the message:

**_``found 2 high severity vulnerabilities``_**
**_``run `npm audit fix` to fix them, or `npm audit` for details``_**

Then after running **_`npm fix audit`_**

**_`+ node-sass@4.12.0`_**
**_`removed 3 packages and updated 3 packages in 109.493s`_**
**_`fixed 2 of 2 vulnerabilities in 11519 scanned packages`_**

So I think you should update your **_`package.json`_** to take this into account.

**Comment by g-div** [comment]
I've just updated `node-sass`, but this isn't enough to solve all high severity vulnerabilities. [This issue](https://github.com/sass/node-sass/issues/2625) seems to be a showstopper.
