### ISSUE TITLE
$ npm install                                                                                                                                               npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!  

### ISSUE THREAD

**Issue by yohannesdev** [wbkd/webpack-starter#425]
$ npm install                                                                                                                                              
 npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!  

how can I solve this. can't seem to run npm start

**Comment by ttiimmaacc** [comment]
Yep this repo is busted
