### ISSUE TITLE
Configuring webpack prod to output multiple html files

### ISSUE THREAD

**Issue by punit11** [wbkd/webpack-starter#44]
Hi there,

Thanks for this great starter kit. I have a little issue. I am trying to configure the webpack prod file to generate multiple HTML files using [this approach](https://stackoverflow.com/questions/49027850/how-to-generate-several-html-files-with-webpack), but when I do the build its simply dumping raw HTML in console.

Can you help ?

Thanks

**Comment by moklick** [comment]
Hey, you can find the solution in the html-webpack-plugin readme https://github.com/jantimon/html-webpack-plugin#generating-multiple-html-files
