### ISSUE TITLE
How to view development version on mobile devices?

### ISSUE THREAD

**Issue by tpkahlon** [wbkd/webpack-starter#64]
I have tried few options like host: '0.0.0.0', port: 8080 in "dev" object but did not work. Any ideas to get it to work so we can test how page displays on various mobile screens?

**Comment by demostanis-worlds** [comment]
Use Chrome DevTools

**Comment by tpkahlon** [comment]
Fixed it by adding following settings in `webpack.config.dev.js` file. You will need to replace host address manually by running `ifconfig | grep inet`.

`
devServer: {
    inline: true,
    host: '192.168.86.29',
    port: 8080
  },
`

**Comment by g-div** [comment]
Host 0.0.0.0 should work as it will expose the server to all listening network interfaces, so you can skip `ifconfig | grep inet`.
