### ISSUE TITLE
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?

### ISSUE THREAD

**Issue by ilhamsj** [wbkd/webpack-starter#98]
`npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?`

**Comment by g-div** [comment]
What's your problem ? Which is the initial situation and what are you running ?

You don't have to call `npm build`manually, the build command is:
```
npm run build
```
as stated in the [README](https://github.com/wbkd/webpack-starter#build-prod-version) as well.
